# Reference: https://github.com/greshake/i3status-rust/blob/v0.22.0/doc/blocks.md

[theme]
theme = "nord-dark"

[icons]
icons = "awesome6"

# [[block]]
#block = "focused_window"
#max_width = 35
#format = "{title}"

#[[block]]
#block = "cpu"
#interval = 2
#format = "{utilization}"

#[[block]]
#block = "load"
#format = "{1m}"
#interval = 15

#[[block]]
#block = "memory"
#format = "{mem_used}"
#icons = true
#interval = 5

[[block]]
block = "net"
interval = 2
#hide_missing = true
#hide_inactive = true

[[block]]
block = "temperature"
# TODO: Only if I have temp sensors

#[[block]]
#block = "backlight"
# TODO: Only if I'm a laptop

[[block]]
block = "pacman"
interval = 600
format = "{both} updates available"
format_singular = "{both} update available"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "yay -Qua"
#hide_when_uptodate = true

[[block]]
block = "battery"
interval = 15
#hide_missing = true
format = " {percentage} ({time})"
full_threshold = 99
full_format = " "

[[block]]
block = "sound"
format = "{volume}"
headphones_indicator = true

[[block]]
block = "time"
format = "%h %d %R"
interval = 15
#on_click = "notify-send \"$(cal)\""

