" Syntax highlighting based on detected language
syntax on

" Iceberg theme - I also use this theme in VSCode
colorscheme iceberg

" Default GUI  Window Geometry
if has("gui_running")
    " Preferred window size
    set lines=29 columns=105
endif

" Show tabs at the top of the editor
set showtabline=2

" Render newlines with '$'
" Render Tabs with '>-'
" Render Trailing Whitespace with '~'
" Extends and Precedes are for Line Wrapping
set list
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<

" Turn on Line numbering
set number

" Highlight all strings that match search
set hlsearch

" Turn on Mouse Aware mode, does lots of stuff
" What we're most interested in is the fact that
" it won't let us highlight the line numbers
set mouse+=a

" Yank and Paste using the system clipboard
set clipboard=unnamedplus

" Convert tabs to spaces
" Tabs are 4 spaces wide
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab

execute pathogen#infect()
filetype plugin indent on
